#!/bin/bash
echo "🫧 Buddy Evolution Plugin"
echo ""
echo "Install directly in Claude Code:"
echo ""
echo "  /plugin marketplace add yazelin/buddy-evolution"
echo "  /plugin install buddy-evolution@buddy-evolution"
echo ""
echo "Then:"
echo "  /buddy-evolution:evo setup    — import your /buddy data"
echo "  /buddy-evolution:evo          — see your buddy's evolution"
echo "  /buddy-evolution:evo sync     — sync to the platform"
echo ""
echo "Platform: https://buddy-evolution-web.vercel.app"
